### ISSUE TITLE
Proposal to revise TAG Charter

### ISSUE THREAD

**Issue by stanblum** [tdwg/tag#31]
The Technical Architecture Group (TAG) is proposing some changes to its charter.  These changes emerged from discussion at its 23 March meeting. (See the [meeting notes](https://github.com/tdwg/tag/blob/master/meetings/2022-03-23-tag-meeting-notes.pdf) if you would like to review the discussion.) 

To review the proposed changes directly, please see:

- the [text of the recommended revisions](https://docs.google.com/document/d/1FKl42i_L-OuwV8iY4PkF7zAw_N0yuLY2IfkGE-7_cs4/edit?usp=sharing) and rationale for changes; and/or
- a "[diff](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d)," which makes the changes visible either side-by-side or as in-line markup.

This proposal was submitted to the Executive Committee (2022-04-22).  With the announcement of this proposal, TDWG has opened a four week period for public comment.  Please add any comments below before 23 May.  If you prefer to make a comment anonymously, please send it to [secretary@tdwg.org](mailto:secretary@tdwg.org), who will post it for you here while keeping your identity private. 

Also, please note that some comments are being posted [here](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d).

**Comment by jar398** [comment]
Dropping the quorum requirement implies, to me, that the TAG can never make any decisions on its own at all, including its own operating procedures or the decision to publish any document or email in the name of the TAG, even if it is only advisory. This is because one or two people could get together and claim they've had a TAG meeting and decided something, without adequate representation, transparency, or process, and the group would have no identity or reputation.  I'm not saying this is likely, but it would be possible and anyone reviewing the TAG's structure will see this.

Similarly I think agendas should be prepared ahead of time and archived after, and at least some advance notice of meetings would be in order, maybe probably 48 hours, so that members can prepare adequately. I know this is a burden on the convener, but it is important to the broader TDWG membership. If it's too hard just don't have a formal committee.

As in any organization the purpose of quorum, notice, and archiving rules is to establish the legitimacy of the entity.  If other committees don't have these I think that is a problem too.  I'm not saying procedure for procedure's sake, and I'm not proposing anything onerous, since the measures I'm suggesting (minimal quorum - 5 people??, basic notice, simple archiving even if just in an email list archive) are common sense measures that are probably going to respected anyhow. But in my opinion, without specific rules to create a bare minimum of identity and legitimacy for the group you might as well just disband the committee, retract the charter, and do everything informally in the names of the individuals involved.

If you want to have meetings without notice or quorum that's fine and perhaps even to be encouraged. Those meetings just shouldn't be done in the name of the TAG or make decisions or communications on its behalf.

Sorry I missed the 3/23 meeting.

**Comment by baskaufs** [comment]
This discussion has been taking place both here and on the [diff page](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d). I believe that for the purposes of maintaining a historical record of the conversation, it would be more easily found here, so I am going to attempt to move the comments here.

**Comment by baskaufs** [comment]
[Comment](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d#r72091980) by @hlapp 

The rationale document says _The minutes are the important thing to be archived and usually the minutes are a reflection of the agenda anyway_. It is very common to post _both_ agenda and minutes for public meetings of public organizations. The minutes may or may not be a reflection of the original agenda, but the actual effort is in the minutes, not the agenda, so I'm not sure on what effort or clutter not posting the agenda is supposed to reduce.

Having said that, I mean my comment to pertain _only_ to public meetings. So I in fact agree that the wording merits changing, but the change I'd make is this:
> Agenda and minutes for all public meetings and all requests, decisions and responses will be posted to the TAG repository.

**Comment by baskaufs** [comment]
[Comment](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d#commitcomment-72078461) by @asimpson-usgs

My interpretation (correct me if I am wrong):
1) it is proposed that there no longer be a minimum/maximum number of members to TAG nor a required quorum for voting (I don't think a quorum should be dropped).
2) the private GitHub repository will be abandoned (I'm OK with this).
3) the formal requirement that agendas be distributed 2 weeks prior will be dropped (too busy, are we? Then delay the meeting date).
4) agendas will no longer be publicly posted (sounds like someone is 'agenda-averse').

**Comment by baskaufs** [comment]
[Comment](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d#commitcomment-72084541) by @baskaufs 

@asimpson-usgs Just for perspective, I've convened at least three TDWG task or interest groups and this is the first time the charter has micromanaged things like how many days ahead the agenda should be distributed. At the first meeting when we discussed these changes, there was general agreement that 14 days ahead of the meeting was an excessively long amount of time and that generally several days ahead was enough time. 

As far as the quorum and number of members are concerned, please read the rationale document. As things currently stand, we have 13 members because there's a large backlog of business and many pending draft standards for which we need expert input. Do I boot 4 people out of the group because we are over 9?

As far as the agenda is concerned, the common practice in most TDWG groups in which I'm involved is to have a combined agenda/notes document that's distributed in advance to group members by email or link through other messaging systems. Notes are taken in that document and then the document is posted as a record in GitHub. See the notes for the first meeting as an example: https://github.com/tdwg/tag/blob/master/meetings/2022-03-23-tag-meeting-notes.pdf . I'm not "agenda-averse", I'm averse to specifying how present and future conveners have to manage the administrative aspects of running the group -- something that does not belong in a charter. 

Keep in mind that the TAG is not a legislative body of some sort. It's primarily a body that offers advice on best practices based on the expertise of the group. Given that, I think it's going to be rare that anything gets "voted" on because the general mode of operation within TDWG has been consensus.

**Comment by baskaufs** [comment]
[Comment](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d#commitcomment-72086152) by @gkampmeier

@asimpson-usgs (my perspective of your list)

1. Given that TDWG works by consensus and the TAG is there to recommend actions to the Exec, there is rarely the need for a formal vote, even at the Exec level. Requiring a quorum to attend any given meeting to make progress (rather than otherwise polling the entire membership if something is that important) could end up impeding progress. With time zone issues and busy schedules even virtual meetings may miss crucial constituencies, so while semi-annual meetings are still in their mandate, providing multiple avenues of discussion is probably more productive than requiring a quorum (plus this is not defined for the purposes of this group [https://www.wikihow.com/Determine-a-Quorum](https://www.wikihow.com/Determine-a-Quorum) 
2. Note that specifying that the TAG has a public repository does not mean that it cannot have a private one if needed, it is just not requiring it.
3. 14 days ROTFL!
4. _Publicly_ posting an agenda is useful when actively inviting outsiders to meetings. Requiring this in the charter when it is not a core principle (inviting outsiders), is additional work if the notes/minutes of the meeting are being posted publicly anyway--there you see what was actually done.

**Comment by baskaufs** [comment]
[Comment](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d#commitcomment-72094496) by @gkampmeier 

@baskaufs regarding the number of members, [TDWG's constitution](https://www.tdwg.org/about/constitution/#article%207.%20functional%20subcommittees_1) states "Each [functional sub]committee shall operate with more than three and fewer than 15 members." so there is already a proscribed upper limit on actual membership. Do you actually openly advertise TAG meetings? Is there any benefit to doing so?

**Comment by baskaufs** [comment]
[Comment](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d#commitcomment-72124207) by @tasilee

It has been over 16 years since @stanblum, @tucotuco and I wrote the TDWG governance texts. I am happily surprised at the small changes. I still remember @tucotuco saying something like "If we don't need to say, don't say it".

Membership: @gkampmeier's point seems to cover it.
Public only repository: OK. I'm unsure why we opted for a private as well, but suspect it was for reasons similar to the recent discussions on reviews.
Agenda in advance: OK.
Agenda public: I would urge the use of @hlapp's phrasing: "Agenda and minutes for all public meetings and all requests, decisions and responses will be posted to the TAG repository."

**Comment by baskaufs** [comment]
[Comment](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d#commitcomment-72211137) by @asimpson-usgs

I now concur with @Tasilee and @gkampmeier. 
(I also confess to having written my comments after looking at the dif page without first reviewing the justifications for the proposed changes.)
I'd also like to express my gratitude to @Tasilee @stanblum and @tucotuco for having written the governance texts so well in the first place.

**Comment by baskaufs** [comment]
[Comment](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d#commitcomment-72218597) by @ghwhitbread

The charter intended to distinguish between formal meetings, as convened within the TDWG conference and open to the membership, and TAG business meetings.   The 14-day notice was included to assist TDWG participants with planning attendance at the annual meeting.

The idea of a separate private repository was to respect the confidentiality of communication with the executive.   But only this one was created and opened in response to calls from the membership.  That does mean that where there is a need for privacy, communication happens out-of-band, and there is no archive available to an incoming TAG.

**Comment by baskaufs** [comment]
[Comment](https://github.com/tdwg/tag/commit/ac1740f9ee117bbd716fa3751f0b6e5f4e582e1d#commitcomment-72229141) by @gkampmeier

Thanks @ghwhitbread for the context clarification of the charter's original intent. I think the pandemic accelerated more on-line meetings, which also make them more accessible (aside from time zone issues and busy schedules that plague them). The revised language gives better flexibility in the charter and recommendations about timing, agendas, notice (aside that such will be given), could be part of a best practices or "accumulated lore" (h/t @baskaufs ) document.

**Comment by baskaufs** [comment]
In order to address concerns raised in the comments above about a small subset of the TAG forcing through decisions without larger input, a revision was made to the proposal requiring a majority of members to participate in any official votes. See [this diff](https://github.com/tdwg/tag/commit/6f179c78d6280c0f9594ef9e09b5393eb3a09037) for the recommended change and the [revised proposal](https://docs.google.com/document/d/1FKl42i_L-OuwV8iY4PkF7zAw_N0yuLY2IfkGE-7_cs4/edit?usp=sharing) for the rationale. This change was supported by TAG members present at the 2022-05-09 Zoom meeting.

**Comment by baskaufs** [comment]
The revisions described [here](https://github.com/tdwg/tag/blob/master/documents/tag_charter_revisions_2022.pdf) were approved by a vote of the Executive Committee on 2022-06-24 and will be made to the charter listed at https://www.tdwg.org/about/committees/tag/
