### ISSUE TITLE
Revise GUID standard

### ISSUE THREAD

**Issue by ghwhitbread** [tdwg/tag#9]
Respond to [Executive Request #90 ](https://github.com/tdwg/exec/issues/90):
> If I remember correctly, at the 2016 conference LSIDs were officially deprecated by TDWG. However, on our website we still recommend them?? The GUID and Life Sciences Identifiers Applicability Statements is still listed as current standard. I think we should ask TAG to retire this standard. A new one should be created, and preferably should refer also to CETAF identifiers.

Advise executive on retirement of the [GUID standard](http://www.tdwg.org/standards/150)

- [ ]   Replace?
- [ ]   Relegate to GUID recommendations/advice pages? 
- [ ]   Both?

**Comment by baskaufs** [comment]
I have changed the title of this from "retire" to "revise". In discussion during the [2022-05-09 TAG meeting](https://github.com/tdwg/tag/blob/master/meetings/2022-05-09-tag-meeting-notes.pdf) there seemed to be considerable consensus that the GUID applicability statement should be revised rather than retired, and that even though LSIDs are no longer considered the preferred identifier type, they are in fairly wide use, so the LSID applicability statement should perhaps also be revised rather than deprecated. 

We do not yet have an official task group to work on this yet, but interest is brewing. So this remains on the agenda.

**Comment by marc-portier** [comment]
+1 on revising over retiring --> at least leaving people with the advise on "what to do now" seems better than trying to pretend bleeding nooses :) 

Looking into the content I would surely want to suggest changing the advise in section [9.4  Recommendations for LSIDs Appearing in RDF](https://www.tdwg.org/static/pages/standards/guid-as/tdwg_lsid_applicability_statement.pdf#page=17)

The current formal advise to use 
* one URI format (the standard URN) as the triple-subject to describe the resource
* yet another format (any proxy-URL) as the preferred way to reference it from elsewhere (i.e. as applied triple-objects)

is hard to square with straightforward usage of knowledge graph technology.  
It also lacks any motivation or attempt at revealing the thought process that gave raise to this outcome.

Towards people dealing with RDF on a regular basis this at least violates [the principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and thus begs for endless referring to this lsid-as document (that finally deals with some approach that is deprecated?) `¯\_(ツ)_/¯` Then try making that not sound as wasting their time?

Even worse, bringing it into practice forces additional processing and thus increases the execution footprint. (As it either assumes reasoning-processing, or extra matching `owl:sameAs+` edges in sparql statements)  


So on this particular point of applying lsid in RDF I would like to change the recommendation to:

1. advise people to mint cool https-uri in a domain they control themselves (with a lot less dns hastle than assumed in lsid land in fact)
2. avoid reinventing the wheel but rather adhere to best practices as to be found around: [W3C best practices](https://www.w3.org/2011/gld/wiki/223_Best_Practices_URI_Construction), [Phil Archer's](https://philarcher.org/diary/2013/uripersistence/) work on [persistent URI](https://joinup.ec.europa.eu/sites/default/files/document/2013-02/D7.1.3%20-%20Study%20on%20persistent%20URIs.pdf) for the EU- and not forgetting about the [range14 issue](https://en.wikipedia.org/wiki/HTTPRange-14)
3. while easily honoring the historic role of lsid by mentioning it as the `dc:identifier <urn:lsid: .... >` for proper provenance and some nostalgia
4. finally simply and rigorously use that URI in your RDF `?subject`s and advocate to have it used in `?object`s likewise

**Comment by marc-portier** [comment]
On the side (regardless of any revision) 

Apparently the `urn:lsid` was never formally [registered as a urn-namespace](https://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml) with [IANA](https://www.iana.org/) ?

**Comment by dhobern** [comment]
I have no desire to revisit the LSID debate, but for completeness I'll
mention a couple of considerations that were in place during the original
TDWG GUID work.

First, it is my understanding too (and was a frustration) that urn:lsid was
never registered with IANA. When the LSID work started in TDWG, the set of
backers for the standard included much bigger players whom we expected
eventually to deal with that.

Secondly - and bear with me explaining this at length - a tension that may
never properly be resolvable is between 1) best practice for a modern
identifier that works on the web and in linked data and 2) the unique
timeframes associated with the science of taxonomy and nomenclature and the
underlying collections. There is no other scientific field that depends so
heavily on work that spans multiple centuries and on the ability to
reference research objects (specimens) from throughout this period.

The TDWG GUID working group 15 years ago, or whenever it was, had high
confidence that the objects we were referencing would exist and need to be
dereferenced in 50 or a 100 years time. Although it feels today like the
very fabric of our knowledge universe, HTTP/HTTPS has existed for less than
40 years and seems unlikely to remain forever. At some point, our global
digital identifier schemes will need to shift to track evolving information
standards.

So, a key question is how any digital identifier scheme we adopt today
should relate to the identifiers we need to attach to physical specimens
collected now. We want our new specimens to be born digital, but we also
want physical labels on the objects. Should these label identifiers somehow
be globally (rather than institutionally) unique and should they be the
same as our web identifiers or should we leave the two decoupled?

For me, one of the key drivers for an LSID-like system at the time was that
LSIDs were a model to achieve global uniqueness that mapped reasonably
naturally onto our domain. And the structure of their text representation
as a series of nested colon-delimited elements is sufficiently distinct
that an LSID is instantly recognisable as such. With some pain, LSIDs could
remain resolvable under any future resolution mechanisms. This meant that
it seemed feasible to label our physical objects with naked (no HTTPS)
LSIDs as digital identifiers that could plausibly always be resolved by
evolving digital data no matter what internet and GUID protocols come to
dominate.

HTTPS URIs will remain recognisable as web identifiers/addresses for a long
time, but a user can never know in advance whether such a URI is an object
identifier or just points to a web page, blog post or whatever.

If we roll forward, there will come a point, not very far in the future,
when <10% of today's HTTPS strings resolve to the intended content. As
institutions change their web architecture, it will be a constant battle
for collections to ensure that their identifiers remain resolvable.

As we roll a little further forward, it seems likely that, just as HTTP is
deprecated for HTTPS in most contexts, HTTPS will be deprecated and
eventually dropped from the standard technology deck that most stakeholders
use. What then will be the path for a user in a collection to link a label
identifier to all the digital knowledge for the specimen?

This is why I for one preferred a scheme with a further resolution step and
one where the type of identifier was distinctive, rather than advocating
just the use of current best practice https-uris.

Our main debate at the time was between the obvious advantages of DOIs (or
some other handle scheme) and LSIDs. The cost for DOIs (clearly the best
planned part of the handle space) seemed eye-watering at the time. Any
other handle solution seemed to require similar investment to support the
socio-technical needs for a robust network. LSIDs seemed to have backers
that made them likely to be a suitable alternative and one that even more
clearly signalled the unique nature of the identifiers. So TDWG adopted
LSIDs. Then the other backers almost instantly disappeared.

Today, I would say that https-uris are so central to all we do digitally
and so important for our data graphs that they seem the natural choice, but
none of the considerations above have changed. Cool https-uris should only
be adopted by institutions that really understand the data sustainability
challenge these represent. Otherwise, using something like DOI may be a
better choice. The future maintenance and mapping problems will remain but
they are more likely to be recognised, reported and handled.

All just FWIW.

Donald

-- 

*Donald Hobern* / ***@***.*** / +61 420511471
Araba Bioscan Project <https://stangeia.hobern.net/araba-bioscan-project/>
/ Pterophoroidea <https://pterophoroidea.hobern.net/> / Alucitoidea
<https://alucitoidea.hobern.net/> / BOLD Australia
<https://bold-au.hobern.net/>
ORCID: 0000-0001-6492-4016 <https://orcid.org/0000-0001-6492-4016> / Blog
<https://stangeia.hobern.net/> / iNaturalist
<https://inaturalist.ala.org.au/people/dhobern> / Flickr
<https://www.flickr.com/photos/dhobern/>/ GitHub
<https://github.com/dhobern> / Twitter <https://twitter.com/dhobern>

**Comment by marc-portier** [comment]
@dhobern thx for your reaction and the broader context it offers. 

I'm totally on board with the (my opportunistic take?) expressed "sense of realism about an ever changing technology space" and the tension it brings to any appreciated attempt "to persistently identify".  Rather then existential, stubborn or dogmatic I obviously also prefer a view of "pragmatic solutions that work / keep working".  And sorry if the tone of my earlier comment might of have made that not obvious.

From that angle I surely think the LSID approach deserves applause: nothing in its design seems to prevent the long lasting role it was aiming for.  There is no reason to abandon using them, and surely hoping they do remain providing a useful link between data expressed over time.  Systems that have done the effort to set up the http-proxy-for-de-referencing approach are hopefully maintaining the effort to assure it keeps doing its work as technological approaches are changing.

At least that is how I read this issue -- a call to revise the applicability statement to allow the driving principles behind the LSID keep playing its optimal role in changing world with new insights and techniques.  As I tried to show -- the recommendations concerning the application of LSID with relation to RDF are currently experienced as hindering rather than enabling its adoption and use.  So why not fix that (and possible other parts) of the applicability statement?

The other observation to make is that persistence is not synonym with unique.  Persistence guarantees ending up at the very same thing intentionally identified. It does not (never can) prevent other identifiers to that same concept to co-exist and take usage preference and thus some share of use in some distinct (possibly fading) spaces.  Having pragmatic and usable ways to keep linking those to each other is a noble goal worthy of our best effort pursuit.

**Comment by baskaufs** [comment]
This issue is being closed and further discussion should take place at https://github.com/tdwg/tag/issues/36 or other more specific issues.
